name: Deploy Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/gradeup-bot:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-test:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: test
      url: https://t.me/gredup_test_bot

    steps:
      - name: Deploy to test server
        uses: appleboy/ssh-action@master
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ADMIN_TELEGRAM_USER_ID: ${{ vars.ADMIN_TELEGRAM_USER_ID }}
          ADMIN_EMAIL: ${{ vars.ADMIN_EMAIL }}
          SMTP_HOST: ${{ vars.SMTP_HOST }}
          SMTP_PORT: ${{ vars.SMTP_PORT }}
          SMTP_USER: ${{ vars.SMTP_USER }}
          SMTP_PASSWORD: ${{ vars.SMTP_PASSWORD }}
          GITHUB_SHA: ${{ github.sha }}
          DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: BOT_TOKEN,ADMIN_TELEGRAM_USER_ID,ADMIN_EMAIL,SMTP_HOST,SMTP_PORT,SMTP_USER,SMTP_PASSWORD,GITHUB_SHA,DOCKERHUB_USERNAME
          script: |
            echo "Starting test deployment..."

            CONTAINER_NAME=gradeup-bot-test
            DATA_DIR=/service/gradeup/test
            mkdir -p $DATA_DIR

            docker pull ${DOCKERHUB_USERNAME}/gradeup-bot:${GITHUB_SHA}
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true

            docker run -d \
              --name $CONTAINER_NAME \
              --restart unless-stopped \
              -v $DATA_DIR:/app/data \
              -e BOT_TOKEN="$BOT_TOKEN" \
              -e ADMIN_TELEGRAM_USER_ID="$ADMIN_TELEGRAM_USER_ID" \
              -e ADMIN_EMAIL="$ADMIN_EMAIL" \
              -e SMTP_HOST="$SMTP_HOST" \
              -e SMTP_PORT="$SMTP_PORT" \
              -e SMTP_USER="$SMTP_USER" \
              -e SMTP_PASSWORD="$SMTP_PASSWORD" \
              ${DOCKERHUB_USERNAME}/gradeup-bot:${GITHUB_SHA}

  deploy-prod:
    needs: [build, deploy-test]
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://t.me/Grade_help_bot

    steps:
      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ADMIN_TELEGRAM_USER_ID: ${{ vars.ADMIN_TELEGRAM_USER_ID }}
          ADMIN_EMAIL: ${{ vars.ADMIN_EMAIL }}
          SMTP_HOST: ${{ vars.SMTP_HOST }}
          SMTP_PORT: ${{ vars.SMTP_PORT }}
          SMTP_USER: ${{ vars.SMTP_USER }}
          SMTP_PASSWORD: ${{ vars.SMTP_PASSWORD }}
          GITHUB_SHA: ${{ github.sha }}
          DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: BOT_TOKEN,ADMIN_TELEGRAM_USER_ID,ADMIN_EMAIL,SMTP_HOST,SMTP_PORT,SMTP_USER,SMTP_PASSWORD,GITHUB_SHA,DOCKERHUB_USERNAME
          script: |
            echo "Starting production deployment..."

            CONTAINER_NAME=gradeup-bot-prod
            DATA_DIR=/service/gradeup/prod
            mkdir -p $DATA_DIR

            docker pull ${DOCKERHUB_USERNAME}/gradeup-bot:${GITHUB_SHA}
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true

            docker run -d \
              --name $CONTAINER_NAME \
              --restart unless-stopped \
              -v $DATA_DIR:/app/data \
              -e BOT_TOKEN="$BOT_TOKEN" \
              -e ADMIN_TELEGRAM_USER_ID="$ADMIN_TELEGRAM_USER_ID" \
              -e ADMIN_EMAIL="$ADMIN_EMAIL" \
              -e SMTP_HOST="$SMTP_HOST" \
              -e SMTP_PORT="$SMTP_PORT" \
              -e SMTP_USER="$SMTP_USER" \
              -e SMTP_PASSWORD="$SMTP_PASSWORD" \
              ${DOCKERHUB_USERNAME}/gradeup-bot:${GITHUB_SHA}
